monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
        nested:
            type: rotating_file
            max_files: 30
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event", "!notifications", "!stock_exchange"]
        console:
            type:   console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!notifications"]
        notifications_logging:
            level: debug
            type: rotating_file
            max_files: 30
            path: "%kernel.logs_dir%/notifications.log"
            channels: [notifications]
        stock_exchange_logging:
            level: debug
            type: rotating_file
            max_files: 30
            path: "%kernel.logs_dir%/stock-exchange.log"
            channels: [stock_exchange]